// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCyDxWUZkdiqzCmQGbtNSezhFLaMsTvaLA',
    appId: '1:398332767854:web:26f7972735ebc05a00807f',
    messagingSenderId: '398332767854',
    projectId: 'bslab-75e89',
    authDomain: 'bslab-75e89.firebaseapp.com',
    storageBucket: 'bslab-75e89.firebasestorage.app',
    measurementId: 'G-EVFVR79JXE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWL-3aFVi1fTsIlixsaZMxwqVPybuN5Xw',
    appId: '1:398332767854:android:a3ad63ec082bd32000807f',
    messagingSenderId: '398332767854',
    projectId: 'bslab-75e89',
    storageBucket: 'bslab-75e89.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3wuW2zOa5ZW07XT-YiGFRhtPYcRYP7gs',
    appId: '1:398332767854:ios:5b190a50dd5a060b00807f',
    messagingSenderId: '398332767854',
    projectId: 'bslab-75e89',
    storageBucket: 'bslab-75e89.firebasestorage.app',
    iosBundleId: 'com.example.userApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD3wuW2zOa5ZW07XT-YiGFRhtPYcRYP7gs',
    appId: '1:398332767854:ios:5b190a50dd5a060b00807f',
    messagingSenderId: '398332767854',
    projectId: 'bslab-75e89',
    storageBucket: 'bslab-75e89.firebasestorage.app',
    iosBundleId: 'com.example.userApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCyDxWUZkdiqzCmQGbtNSezhFLaMsTvaLA',
    appId: '1:398332767854:web:17e3337d045d2fad00807f',
    messagingSenderId: '398332767854',
    projectId: 'bslab-75e89',
    authDomain: 'bslab-75e89.firebaseapp.com',
    storageBucket: 'bslab-75e89.firebasestorage.app',
    measurementId: 'G-Y7WJQ3QNWG',
  );
}
